[package]
name = "cbakd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
interprocess = "1.1.1"
rayon = "1.5.3"
regex = "1.6.0"
serde = { version = "1.0.145", features = ["serde_derive"] }
toml = "0.5.9"
